##########################################################
###################  开发环境dev  ###################
##########################################################
spring:
  profiles: dev
  datasource:
      url: jdbc:mysql://192.168.30.245:3306/tcjdb?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
      username: root
      password: 1qaz@WSX

      filters: log4j,wall,mergeStat
logging:
  level.root: info
  level.com.stylefeng: debug
  path: logs/
  file: guns.log
###################  项目启动端口  ###################
server:
  port: 8080

###################  图片服务器   ###################
default:
  path: Z:/
  server: http://172.16.0.3:8081/
  fileAddress: tcj