##########################################################
###################  开发环境dev  ###################
##########################################################
spring:
  profiles: https-dev
  datasource:
      url: jdbc:mysql://192.168.30.245:3306/tcjdb?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
      username: root
      password: 1qaz@WSX

      filters: log4j,wall,mergeStat
logging:
  level.root: info
  level.com.stylefeng: debug
  path: logs/
  file: guns.log
###################  项目启动端口  ###################
server:
  port: 8080

###################  图片服务器   ###################
default:
  path: Z:/
  server: http://172.16.0.3:8081/
  fileAddress: tcj

 ###################  配置https   ###################
#https端口号.
server.port: 8082
#证书的路径.
server.ssl.key-store: classpath:keystore.p12
#证书密码，请修改为您自己证书的密码.
server.ssl.key-store-password: 123456
#秘钥库类型
server.ssl.keyStoreType: PKCS12
#证书别名
server.ssl.keyAlias: tomcat
